import type { Opportunity } from "./types";

/** Mock backend payload. Replace via getOpportunities() in service.ts. */
export const mockOpportunities: Opportunity[] = [
  {
    id: "mb53qf",
    source: "Highlander Hub",
    source_id: "9876543",
    source_url: "https://example.com/highlander-hub/fall-campus-cleanup",
    title: "Fall Campus Cleanup",
    category: "environmental",
    description:
      "Join fellow NJIT students for a campus cleanup and help make our community greener.",
    starts_at: "2026-10-16T18:00:00-04:00",
    ends_at: "2026-10-16T20:00:00-04:00",
    location: "Campus Center Ballroom A",
    org_name: "Association for Computing Machinery",
    organizer_email: "someone@njit.edu",
    image_url: "/images/opportunities/fall-campus-cleanup.jpg",
  },
  {
    id: "7ka9qp",
    source: "Discord",
    source_id: "abc123",
    source_url: "https://example.com/discord/acm-cleanup",
    title: "ACM Cleanup",
    category: "environmental",
    description: "ACM cleanup this Friday at 6 PM. Volunteers are needed!",
    starts_at: "2026-10-16T18:00:00-04:00",
    ends_at: "2026-10-16T20:00:00-04:00",
    location: "Campus Center Ballroom A",
    org_name: "ACM",
    organizer_email: "",
    image_url: "/images/opportunities/fall-campus-cleanup.jpg",
  },
  {
    id: "r1lab9",
    source: "Highlander Hub",
    source_id: "1200451",
    source_url: "https://example.com/highlander-hub/undergrad-research-assistants",
    title: "Undergraduate Research Lab Assistants",
    category: "research",
    description:
      "Help graduate researchers in the Biomedical Engineering lab prepare samples, log data, and present findings at the fall symposium.",
    starts_at: "2026-10-08T13:00:00-04:00",
    ends_at: "2026-10-08T16:00:00-04:00",
    location: "Fenster Hall 470",
    org_name: "NJIT Biomedical Engineering",
    organizer_email: "bme@njit.edu",
    image_url: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800&q=70",
  },
  {
    id: "r2ai44",
    source: "External",
    source_id: "ext-88",
    source_url: "https://example.com/external/ai-for-good-datathon",
    title: "AI for Good Datathon Mentors",
    category: "research",
    description:
      "Guide high-school teams as they explore open climate datasets and build their first machine learning models.",
    starts_at: "2026-10-24T10:00:00-04:00",
    ends_at: "2026-10-24T15:00:00-04:00",
    location: "GITC Atrium",
    org_name: "Women in Computing Society",
    organizer_email: "",
    image_url: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=70",
  },
  {
    id: "t1math",
    source: "Highlander Hub",
    source_id: "1200510",
    source_url: "https://example.com/highlander-hub/calculus-peer-tutoring",
    title: "Calculus Peer Tutoring Night",
    category: "tutoring",
    description:
      "Share your calculus know-how with first-year students before midterms. Snacks and study guides provided.",
    starts_at: "2026-10-06T18:30:00-04:00",
    ends_at: "2026-10-06T20:30:00-04:00",
    location: "Central King Building 116",
    org_name: "Math Learning Center",
    organizer_email: "mlc@njit.edu",
    image_url: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&q=70",
  },
  {
    id: "t2read",
    source: "Discord",
    source_id: "dsc-445",
    source_url: "https://example.com/discord/newark-reading-buddies",
    title: "Newark Reading Buddies",
    category: "tutoring",
    description:
      "Read with elementary students at a local Newark library branch every Saturday morning.",
    starts_at: "2026-10-10T10:00:00-04:00",
    ends_at: "2026-10-10T12:00:00-04:00",
    location: "Newark Public Library, North Branch",
    org_name: "Society of Women Engineers",
    organizer_email: "",
    image_url: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&q=70",
  },
  {
    id: "e2tree",
    source: "External",
    source_id: "ext-102",
    source_url: "https://example.com/external/branch-brook-tree-planting",
    title: "Branch Brook Park Tree Planting",
    category: "environmental",
    description:
      "Plant native saplings with the Newark parks team and learn how urban canopies cool our city.",
    starts_at: "2026-10-31T09:00:00-04:00",
    ends_at: "2026-10-31T12:00:00-04:00",
    location: "Branch Brook Park, Newark",
    org_name: "Newark Green Team",
    organizer_email: "",
    image_url: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800&q=70",
  },
  {
    id: "e3garden",
    source: "Discord",
    source_id: "dsc-501",
    source_url: "https://example.com/discord/rooftop-garden-harvest",
    title: "Rooftop Garden Harvest",
    category: "environmental",
    description:
      "Help harvest and compost at the campus rooftop garden. All produce goes to the student food pantry.",
    starts_at: "2026-10-04T16:00:00-04:00",
    ends_at: "2026-10-04T18:00:00-04:00",
    location: "Campus Center Rooftop",
    org_name: "NJIT Sustainability Club",
    organizer_email: "",
    image_url: "",
  },
  {
    id: "c1food",
    source: "Highlander Hub",
    source_id: "1200602",
    source_url: "https://example.com/highlander-hub/food-pantry-shift",
    title: "Highlander Pantry Volunteer Shift",
    category: "community service",
    description:
      "Stock shelves, greet visitors, and help fellow students access free groceries at the Highlander Pantry.",
    starts_at: "2026-10-07T12:00:00-04:00",
    ends_at: "2026-10-07T15:00:00-04:00",
    location: "Campus Center 245",
    org_name: "Highlander Pantry",
    organizer_email: "pantry@njit.edu",
    image_url: "https://images.unsplash.com/photo-1593113598332-cd288d649433?w=800&q=70",
  },
  {
    id: "c2coat",
    source: "External",
    source_id: "ext-140",
    source_url: "https://example.com/external/winter-coat-drive",
    title: "Winter Coat Drive Sorting",
    category: "community service",
    description:
      "Sort and fold donated coats for families across Essex County ahead of the cold season.",
    starts_at: "2026-11-14T11:00:00-05:00",
    ends_at: "2026-11-14T14:00:00-05:00",
    location: "St. Columba Community Hall",
    org_name: "Essex Neighbors United",
    organizer_email: "",
    image_url: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=800&q=70",
  },
  {
    id: "c3senior",
    source: "Discord",
    source_id: "dsc-612",
    source_url: "https://example.com/discord/tech-help-for-seniors",
    title: "Tech Help for Seniors",
    category: "community service",
    description:
      "Teach older neighbors how to video-call family, spot scams, and use their smartphones with confidence.",
    starts_at: "2026-10-20T14:00:00-04:00",
    ends_at: "2026-10-20T16:00:00-04:00",
    location: "Ironbound Senior Center",
    org_name: "ACM-W",
    organizer_email: "",
    image_url: "https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=800&q=70",
  },
  {
    id: "m1lead",
    source: "Highlander Hub",
    source_id: "1200730",
    source_url: "https://example.com/highlander-hub/girlhacks-logistics-team",
    title: "GirlHacks Logistics Team",
    category: "management",
    description:
      "Coordinate check-in, meals, and room schedules for GirlHacks 2026. Great for aspiring project managers.",
    starts_at: "2026-10-12T17:00:00-04:00",
    ends_at: "2026-10-12T19:00:00-04:00",
    location: "GITC 1400",
    org_name: "NJIT GirlHacks",
    organizer_email: "team@njitgirlhacks.com",
    image_url: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&q=70",
  },
  {
    id: "m2fair",
    source: "External",
    source_id: "ext-171",
    source_url: "https://example.com/external/stem-fair-volunteer-leads",
    title: "STEM Fair Volunteer Leads",
    category: "management",
    description:
      "Lead a small team of volunteers running hands-on science booths for local middle schoolers.",
    starts_at: "2026-11-07T09:00:00-05:00",
    ends_at: "2026-11-07T13:00:00-05:00",
    location: "Newark Museum of Art",
    org_name: "Newark STEM Alliance",
    organizer_email: "",
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&q=70",
  },
  {
    id: "m3hub",
    source: "Discord",
    source_id: "dsc-733",
    source_url: "https://example.com/discord/club-fair-booth-captains",
    title: "Club Fair Booth Captains",
    category: "management",
    description:
      "Organize the booth layout and volunteer rotations for the spring club fair planning kickoff.",
    starts_at: "2026-10-28T18:00:00-04:00",
    ends_at: "2026-10-28T19:30:00-04:00",
    location: "Campus Center Ballroom B",
    org_name: "Student Senate",
    organizer_email: "",
    image_url: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=800&q=70",
  },
];
